version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pgtest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: monitoramento
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - db

  agent-web:
    build: ./agent-web
    container_name: agent-web
    depends_on:
      - db
    restart: always

volumes:
  pg_data:
  grafana_data:
